stages:
  - deploy

deploy to development:
  image: ubuntu:latest
  stage: deploy
  environment:
    name: development
    url: https://veads-dev.ontwikkel.it
  only:
    - development
  script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null daanvanberkel@server1.daanvanberkel.nl "cd /home/daanvanberkel/sites/veads-dev.ontwikkel.it/ && git pull && composer install && php artisan migrate"

deploy to master:
  image: ubuntu:latest
  stage: deploy
  environment:
    name: master
    url: https://veads.ontwikkel.it
  only:
    - master
  script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null daanvanberkel@server1.daanvanberkel.nl "cd /home/daanvanberkel/sites/veads.ontwikkel.it/ && git pull && composer install && php artisan migrate"
